### ISSUE TITLE
The YouTube feed is returning https://youtube.com/devicesupport 

### ISSUE THREAD

**Issue by ChipPappas** [christianvuerings/jquery-lifestream#196]
It appears that the YouTube feed is no longer working correctly. The feed returns https://youtube.com/devicesupport

**Comment by christianv** [comment]
@ChipPappas indeed, some more info on this:

http://youtube-eng.blogspot.com/2014/03/committing-to-youtube-data-api-v3_4.html
http://stackoverflow.com/questions/29752447/how-to-get-a-youtube-channel-rss-feed-after-2015-april-20-without-v3-api

**Comment by ChipPappas** [comment]
Thank you Christian


Chip Pappas
Olive Development, LLC
chip.pappas@olivedevelopment.com<mailto:chip.pappas@olivedevelopment.com>
w 603/430-6287
m 603/682-5773

On Jun 1, 2015, at 2:38 PM, Christian Vuerings <notifications@github.com<mailto:notifications@github.com>> wrote:


@ChipPappas<https://github.com/ChipPappas> indeed, some more info on this:

http://youtube-eng.blogspot.com/2014/03/committing-to-youtube-data-api-v3_4.html
http://stackoverflow.com/questions/29752447/how-to-get-a-youtube-channel-rss-feed-after-2015-april-20-without-v3-api

**Comment by christianvuerings** [comment]
@ChipPappas this should have now been fixed in https://github.com/christianvuerings/jquery-lifestream/releases/tag/0.5.4

Big thanks to @davidlimcheng
