### ISSUE TITLE
Facebook Page feed not showing

### ISSUE THREAD

**Issue by mMoovs** [christianvuerings/jquery-lifestream#198]
I just noticed that Lifestream is not showing my facebook page feed. That's actually the only feed I'm currently trying to show with this plugin.

I was using the 0.5.2 version of the script and looks like Facebook deprecated the RSS feed functionality yesterday.

So, I then changed the script file to the new one since it had been updated few days ago (from 0.5.2 to 0.5.3), and it's using some facebooky.herokuapp.com? Well that doesn't load anything, it sure tries but for example now, after more than 5 minutes waiting, it hasn't gotten any results.

Is there anything to do?

**Comment by christianv** [comment]
@mMoovs until recently the `facebooky` solution worked but now they've disabled the RSS feed completely. I guess the only other solution will be to actually scrape the page.

https://www.facebook.com/feeds/page.php?format=rss20&id=54557413386
https://www.facebook.com/BillJohnsonMinistries

**Comment by suragprajapati** [comment]
I am still struggling with scraping the page.  Not sure how to handle this. Any help on this will be appreciated.

**Comment by ohliu** [comment]
Hi Christian, thanks for the wonderful plug-in. Just wondering if you have figured out a way to make Facebook work again. Let me know if I can help in any way.

**Comment by christianv** [comment]
Hi @ohliu we actually have someone (@davidlimcheng) who recently started working on making a scraper which would allow us to surface the data in an API.

We'll be updating https://github.com/christianv/facebooky

**Comment by PatriceBois** [comment]
Any updates on this problem? not seem to be working right now... I got an Application error.

**Comment by christianv** [comment]
@PatriceBois afaik @davidlimcheng is still working on a fix for this.

**Comment by davidlimcheng** [comment]
Hi @PatriceBois , yes - still working on this problem!

**Comment by romymk** [comment]
Hi all... any updates?

**Comment by christianvuerings** [comment]
@romymk we just fixed this as part of 0.5.5 - d8ec650fd73d6314fdf391d370fe96b5bd175804

We now also use the actual page name.
E.g. for `www.facebook.com/nike` we now use `nike`

Also see https://github.com/christianvuerings/jquery-lifestream/releases/tag/0.5.5 for some more limitiations.

If someone does need more features, I would recommend writing their own scraper. A good start is at https://github.com/christianvuerings/facebooky (which we use)

**Comment by romymk** [comment]
@christianvuerings Thanks much. Will have a look.

**Comment by mMoovs** [comment]
Great @christianvuerings, it's working now! Thanks!

**Comment by mMoovs** [comment]
Or atleast worked for one day.. Now it returns empty array for posts, something changed in the herokuapp? Or is it really the low uptime? So the data is not available all the time? Sigh

**Comment by christianvuerings** [comment]
@mMoovs The reason is that they keep changing their DOM all the time, I would suggest that you build and use your own proxy instead if you require this to work in production.

**Comment by christianvuerings** [comment]
Looks like the herokuapp is getting flooded, since we're open source and aren't paying for it, I would suggest people try writing / hosting their own scraper and put it on a paid server.
