### ISSUE TITLE
Facebook Feeds Not Showing

### ISSUE THREAD

**Issue by pinecreativelabs** [christianvuerings/jquery-lifestream#204]
Facebook feeds don't show up at all.

**Comment by pinecreativelabs** [comment]
Whoops! Just saw you fixed this. Disregard this.

**Comment by christianvuerings** [comment]
@pinecreativelabs yes, just realise it's extremely limited (only 4 last posts).
More info at https://github.com/christianvuerings/jquery-lifestream/releases/tag/0.5.5
